#!/usr/bin/env python3
"""
Generate _bundle.js — ein concatenierbares JS-Modul mit allen Elite-Motto-Daten.

Wird von _src/build.sh vor der Konkatenation aufgerufen. Output:
  var ELITE_MOTTO_DATA = { 'motto-age': {...}, ... };
  function getEliteData(motto, ageGroup) { ... }

So konsumiert kindergeburtstag.jsx die Daten:
  const elite = getEliteData('feuerwehr', 'mittel');
  if (elite) { /* render preparationWeeks, sosScenarios, etc */ }
"""
import json, sys, os, io
sys.stdout.reconfigure(encoding='utf-8')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

SLOTS = [
    ('feuerwehr', 'klein'),
    ('feuerwehr', 'mittel'),
    ('feuerwehr', 'gross'),
    ('einhorn', 'klein'),
    ('einhorn', 'mittel'),
    ('einhorn', 'gross'),
    ('safari', 'klein'),
    ('safari', 'mittel'),
    ('safari', 'gross'),
    ('dino', 'klein'),
    ('dino', 'mittel'),
    ('dino', 'gross'),
    ('piraten', 'klein'),
    ('piraten', 'mittel'),
    ('piraten', 'gross'),
    ('weltraum', 'klein'),
    ('weltraum', 'mittel'),
    ('weltraum', 'gross'),
    ('detektiv', 'klein'),
    ('detektiv', 'mittel'),
    ('detektiv', 'gross'),
    ('meerjungfrau', 'klein'),
    ('meerjungfrau', 'mittel'),
    ('meerjungfrau', 'gross'),
    ('dschungel', 'klein'),
    ('dschungel', 'mittel'),
    ('dschungel', 'gross'),
    ('feen', 'klein'),
    ('feen', 'mittel'),
    ('feen', 'gross'),
]

data_map = {}
for motto, age in SLOTS:
    path = os.path.join(SCRIPT_DIR, f'{motto}-{age}.json')
    if not os.path.exists(path):
        print(f'WARN: {path} nicht gefunden — skip')
        continue
    with io.open(path, encoding='utf-8') as f:
        data_map[f'{motto}-{age}'] = json.load(f)

# Output JS module
out_path = os.path.join(SCRIPT_DIR, '_bundle.js')
js_data = json.dumps(data_map, ensure_ascii=False, indent=2)

js_module = f"""// _src/elite-motto-data/_bundle.js
// AUTO-GENERATED by _generate_bundle.py — DO NOT EDIT MANUALLY.
// Source: _src/elite-motto-data/<motto>-<age>.json
// Regeneriert via: python3 _src/elite-motto-data/_generate_bundle.py

var ELITE_MOTTO_DATA = {js_data};

function getEliteData(motto, ageGroup) {{
  // Returns elite-motto JSON for a motto+ageGroup combination, or null if not available.
  // The Planer falls back to legacy SZ_THEMES/kindergeburtstag-data.js when null.
  if (!motto || !ageGroup) return null;
  var key = motto + '-' + ageGroup;
  return ELITE_MOTTO_DATA[key] || null;
}}

function hasEliteData(motto, ageGroup) {{
  return getEliteData(motto, ageGroup) !== null;
}}

function listEliteSlots() {{
  return Object.keys(ELITE_MOTTO_DATA);
}}
"""

with io.open(out_path, 'w', encoding='utf-8') as f:
    f.write(js_module)

print(f'Generated: {out_path}')
print(f'Slots: {len(data_map)}')
for k in data_map: print(f'  - {k}')
print(f'Bundle size: {len(js_module):,} chars ({len(js_module)/1024:.1f}KB)')
